# Generated by Django 6.0.4 on 2026-04-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_interval_miles', models.IntegerField(blank=True, null=True)),
                ('default_interval_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('current_mileage', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-year', 'make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'vehicle_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('mileage_at_service', models.IntegerField(blank=True, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='core.vehicle')),
            ],
            options={
                'db_table': 'maintenance_logs',
                'ordering': ['-log_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.vehicletype'),
        ),
        migrations.CreateModel(
            name='LogService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('log', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, related_name='log_services', to='core.maintenancelog')),
                ('service_type', models.ForeignKey(db_column='service_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='log_services', to='core.servicetype')),
            ],
            options={
                'db_table': 'log_services',
                'unique_together': {('log', 'service_type')},
            },
        ),
    ]
