# Generated by Django 6.0.4 on 2026-04-24

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def assign_existing_records_to_single_user(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    Vehicle = apps.get_model("core", "Vehicle")
    ServiceType = apps.get_model("core", "ServiceType")

    if User.objects.count() != 1:
        return

    owner = User.objects.order_by("pk").first()
    Vehicle.objects.filter(owner__isnull=True).update(owner=owner)
    ServiceType.objects.filter(owner__isnull=True).update(owner=owner)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_vehicle_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="service_types",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(
            assign_existing_records_to_single_user,
            reverse_code=noop_reverse,
        ),
        migrations.AddConstraint(
            model_name="servicetype",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"),
                name="unique_service_type_name_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=Q(vin__isnull=False),
                fields=("owner", "vin"),
                name="unique_vehicle_vin_per_owner",
            ),
        ),
    ]
